### PR TITLE
fix some feedback re: sftp deployment

### PR DESCRIPTION
**Pull request by mahmoudimus**
ping @mjallday (this is for some of the @jakeyr's feedback yesterday).

### CODE REVIEW

**Comment by mjallday** [comment]
this mirrors the http stuff right? lgtm if so. i don't see `vg_vault_sftp_config_override` being created anywhere however.

**Comment by mahmoudimus** [comment]
@mjallday that's because that's a convenience variable (not used in the role). Here's where it's used: https://github.com/lendup/vg-vault-ops/blob/ansible/plays/vault_http.yml#L12-L17

**Comment by jakeyr** [comment]
you also need to create the override directory in the sftp tasks, e.g.:

```yaml
    - name: create override directory
      file: path={{ vg_vault_config_overrides_dir }} state=directory owner={{ vg_vault_user }} group={{ vg_vault_group }} recurse=yes
      tags: [vault, vault-config]
```

i am currently doing this in the outer playbook, FYI

**Comment by mahmoudimus** [comment]
@jakeyr ah makes sense, let me do that.

**Comment by mjallday** [comment]
@mahmoudimus throw it in the common.yml since it's the same for both services.

**Comment by mahmoudimus** [comment]
done here https://github.com/verygood-ops/verygood.vault/commit/3de60e40b40ea370eb20298ce4030827541a9025 and https://github.com/verygood-ops/verygood.vault/commit/2b8baee78d87786a31087651c3a18563fff25fbb

**Pull request merged**
